---
# This task feeds messags to Slack about what Ansible is doing
- name: "Send Slack message to {{ slack_channel }} indicating Ansible play information"
  slack:
    msg: "{{ item }}"
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
  delegate_to: localhost
  ignore_errors: true
  run_once: true
  loop:
    - "****************\n*Starting new Ansible play...*\n```Ansible Role: {{ role_name }}\nAnsible Task: {{ deployment_task }}\nTarget Host: {{ ansible_fqdn }}\nStart Time: {{ ansible_date_time.iso8601 }}```"
  when:
    - slack_token is defined
    - slack_channel is defined
